fix(husky): commit check final finishing and testing on another branch

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,27 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+current_branch=`git rev-parse --abbrev-ref HEAD`
+if [[ $current_branch =~ master|main ]]; then
+    message="Please don't commit directly to $current_branch."
+    echo -e "\033[1;31mERROR: $message\033[0m";
+    exit 1
+fi
+
+repo_dir=`git rev-parse --show-toplevel`
+
+message="[Policy] Checking code in $repo_dir with lint..."
+# echo with color: https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797
+echo -e "\033[1;34mInfo: $message\033[0m"
+
 npx --no-install lint-staged
+
+if [ $? -eq 1 ]; then
+    message="[Policy] lint check failed, please use lint to format your code."
+    echo -e "\033[1;31mERROR: $message\033[0m";
+    exit 1
+else
+    message="[Policy] Passed lint checking."
+    echo -e "\033[1;32mOK: $message\033[0m"
+    exit 0
+fi
